### ISSUE TITLE
为什么提示： System.FormatException: 已标识项中有一项的格式无效。

### ISSUE THREAD

**Issue by XiaoFuDieZZZ** [Xzonn/PCTRTools#4]
![PixPin_2024-10-25_11-22-07](https://github.com/user-attachments/assets/35fc0e05-3cd5-40b4-8ebd-0e8a147f07f5)
文本是从魂银里导出来的 /a/0/2/7 
码表是从你那边下载的
命令也是一样，就是报错。
![图片](https://github.com/user-attachments/assets/bdf1eb2f-110b-451f-afeb-fa862380bb0d)

**Comment by Xzonn** [comment]
无法复现，建议打包附件上传。

**Comment by XiaoFuDieZZZ** [comment]
[工具+文本.zip](https://github.com/user-attachments/files/17516609/%2B.zip)
这个是附件，试了挺多次失败了

**Comment by Xzonn** [comment]
文件数目不匹配，这是哪里来的文本？

**Comment by XiaoFuDieZZZ** [comment]
> 文件数目不匹配，这是哪里来的文本？

这个是风暴银（国外的英文改版）的文本，我想汉化他

**Comment by XiaoFuDieZZZ** [comment]
github好像不允许上传50m以上的文件，不然我就上传那个源nds文件了😂

**Comment by Xzonn** [comment]
下载[最新开发版本](https://github.com/Xzonn/PCTRTools/actions/runs/11529590779/artifacts/2107160128)，导入导出命令最后加一个 `-g 4`。
